project_id = "lksseuxzptdqtgppxnlo"

[functions.send-invitation-email]
verify_jwt = true

[functions.analyze-receipt]
verify_jwt = true

[functions.send-report-email]
verify_jwt = true

[functions.approve-report]
verify_jwt = true

[functions.extract-policy-text]
verify_jwt = false

[functions.notify-missing-grades]
verify_jwt = true

[functions.notify-travel-request]
verify_jwt = true

[functions.notify-travel-decision]
verify_jwt = true
